/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicIdIndexRouteImport } from './routes/topics.$topicId.index'
import { Route as TopicsTopicIdLessonIdRouteImport } from './routes/topics.$topicId.$lessonId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdIndexRoute = TopicsTopicIdIndexRouteImport.update({
  id: '/topics/$topicId/',
  path: '/topics/$topicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdLessonIdRoute = TopicsTopicIdLessonIdRouteImport.update({
  id: '/topics/$topicId/$lessonId',
  path: '/topics/$topicId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/test': typeof TestRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/$lessonId': typeof TopicsTopicIdLessonIdRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/test': typeof TestRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicId/$lessonId': typeof TopicsTopicIdLessonIdRoute
  '/topics/$topicId': typeof TopicsTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/test': typeof TestRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/$lessonId': typeof TopicsTopicIdLessonIdRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/test'
    | '/topics/'
    | '/topics/$topicId/$lessonId'
    | '/topics/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/test'
    | '/topics'
    | '/topics/$topicId/$lessonId'
    | '/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/test'
    | '/topics/'
    | '/topics/$topicId/$lessonId'
    | '/topics/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  TestRoute: typeof TestRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TopicsTopicIdLessonIdRoute: typeof TopicsTopicIdLessonIdRoute
  TopicsTopicIdIndexRoute: typeof TopicsTopicIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/': {
      id: '/topics/$topicId/'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId/'
      preLoaderRoute: typeof TopicsTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/$lessonId': {
      id: '/topics/$topicId/$lessonId'
      path: '/topics/$topicId/$lessonId'
      fullPath: '/topics/$topicId/$lessonId'
      preLoaderRoute: typeof TopicsTopicIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  TestRoute: TestRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TopicsTopicIdLessonIdRoute: TopicsTopicIdLessonIdRoute,
  TopicsTopicIdIndexRoute: TopicsTopicIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
